version: "3.7"

services:
    web-server:
        container_name: sikode_nginx
        image: nginx:alpine
        depends_on:
            - app
        volumes:
            - ./latianLaravel:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
            - ./certbot/conf:/etc/nginx/ssl
            - ./certbot/data:/var/www/le/letsencrypt
            - ./dhparam:/etc/nginx/dhparam
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        networks:
            - apep

    certbot:
        image: certbot/certbot:latest
        command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email pasargm@gmail.com --agree-tos --no-eff-email -d api-beken.sikode.my.id
        volumes:
            - ./certbot/conf/:/etc/letsencrypt
            - ./certbot/logs/:/var/log/letsencrypt
            - ./certbot/data:/usr/share/nginx/html/letsencrypt
        depends_on:
            - web-server

    app:
        container_name: sikode_laravel
        depends_on:
            - db
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./latianLaravel:/var/www
        working_dir: /var/www
        networks:
            - apep

    db:
        container_name: sikode_database
        image: mysql:5.7
        ports:
            - 3500:3306
        volumes:
            - dbvolume:/var/lib/mysql/
        #      - ./docker-volumes-data/db:/etc/mysql/my.cnf
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: yayasanp333mudaTERSESAT666
        networks:
            - apep

networks:
    apep:
        driver: bridge

volumes:
    dbvolume:
        driver: local
